development:
  adapter: mysql
  database: shareaware_dev
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  database: shareaware
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: shareaware
  host: localhost
  username: root
  password:
